### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by mariogmz** [Matjaxon/react-twilio-ip-messaging#1]
Hello,
I'm struggling while trying to load this module, I get the next error:

```
ERROR in ./~/twilio-ip-messaging-react/ip_chat_client.jsx
Module parse failed: /Users/mariogomez/Code/reduxtagram/node_modules/twilio-ip-messaging-react/ip_chat_client.jsx Unexpected token (56:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (56:8)
    at Parser.pp$4.raise (/Users/mariogomez/Code/reduxtagram/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/mariogomez/Code/reduxtagram/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/mariogomez/Code/reduxtagram/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/mariogomez/Code/reduxtagram/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/mariogomez/Code/reduxtagram/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/mariogomez/Code/reduxtagram/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/mariogomez/Code/reduxtagram/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/mariogomez/Code/reduxtagram/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Users/mariogomez/Code/reduxtagram/node_modules/webpack/node_modules/acorn/dist/acorn.js:1861:32)
    at Parser.pp$3.parseExprAtom (/Users/mariogomez/Code/reduxtagram/node_modules/webpack/node_modules/acorn/dist/acorn.js:1796:19)
 @ ./client/components/Main.js 25:30-66
```

**webpack.config.js**

```
webpackConfig.module.loaders = [{
  test    : /\.jsx?$/,
  exclude : /node_modules/,
  loader  : 'babel',
  query   : {
    cacheDirectory : true,
    plugins        : ['transform-runtime'],
    presets        : ['es2015', 'stage-0', 'react']
  }
}, {
  test   : /\.json$/,
  loader : 'json'
}]
```

Don't know what's going on, can someone please tell me what I'm doing wrong.
For reference I'm using https://github.com/davezuko/react-redux-starter-kit, but I even tried including this component inside another react app.

**Comment by Matjaxon** [comment]
Hi Mario,

This looks like a webpack issue.   I've included the loaders that I use in the component below.  I would recommend making sure that you have all of these in yours as well.

```
module: {
    loaders: [
      {
        test: [/\.jsx?$/, /\.js?$/],
        exclude: /node_modules/,
        loader: 'babel',
        query: {
          presets: ["es2015","react"]
        }
      },
      {
        test: /\.css$/,
        loader: "style-loader!css-loader"
      }
    ]
  },
```

**Comment by santhi-nyros** [comment]
Hi Matjaxon , I am also getting same issue like ,

./~/twilio-ip-messaging-react/ip_chat_client.jsx
Module parse failed: /home/nyros/Documents/ProjectName/node_modules/twilio-ip-messaging-react/ip_chat_client.jsx Unexpected token (56:8)
You may need an appropriate loader to handle this file type.
|     if (this.state.messagingClient) {
|       return (
|         <div>
|           <IPChatChannelManager
|             messagingClient={this.state.messagingClient}

I have added loaders in webpack also but still getting same error.
